### ISSUE TITLE
km/h speed in IC not aligned with eon

### ISSUE THREAD

**Issue by tb205gti** [BogGyver/openpilot#102]
When running IC integration, the ACC/PCC speed set in the IC does not align with the eon. eg. set the cruise speed to 90 km/h - the IC shows 88 km/h. try and increase the speed 1km/h by pushing the stalk up - still shows 88km/h, but eon shows 91 - and car maintains 91km/h. Do it again at IC will show 91 - but eon 92km/h.

**Comment by BogGyver** [comment]
if they don't push 0.6.5 soon for another merge i will start fixing this. it's not an "easy" one as Tesla does not have a default unit of measure, so we need to send kph when the car expects kph and mph when the car expects MPH. We would have to rewrite PCC/ACC to work with variable units (right now they operate in kph) and then interface with the car the right way. Not very complicated but many changes so  will only attempt in a downtime.

**Comment by BogGyver** [comment]
Fixed in release (https://github.com/BogGyver/openpilot/commit/126567bdba2f29584d9b0fe3e194bd06957f3c58)
