### ISSUE TITLE
Suggestion: Port to Unix & CUDA (e.g. Nvidia Jetson family)

### ISSUE THREAD

**Issue by Hurricane31337** [BogGyver/openpilot#159]
As I'm interested to retrofit the Tesla AP1 functionality with OpenPilot, I wondered why the Tesla branch still relies on a smartphone instead of more capable hardware like the Jetson AGX or Jetson TX2, which essentially cost the same:
https://developer.nvidia.com/embedded/jetson-agx-xavier-developer-kit

For other cars without screens it might make sense to use the screen of the phone combined with its cameras, but in the case of a Tesla Model S, we already have screens (which are already being used by OpenPilot) and we could mount more cameras, radars and other sensors around the car, just like on AP2+. By using a modular platform like the Nvidia Jetson family, we could even do it just like Tesla and enable/disable functionality depending on available processing power (train several separate NNs for traffic signs, cars, traffic lights, ...). The user could then easily upgrade to the latest Jetson platform or even a Mini-ITX PC with an RTX 2080 if wanted, as everything would run on a real time Unix and CUDA instead of Android.

I think this could drastically improve the modularity and capabilities of this project in the following years, as the user could easily upgrade the Jetson board behind the glove box and the project wouldn't need to hold back because of the limited processing power of the phone.

**Comment by tb205gti** [comment]
We do have it running on jetson.. it needs to be thoroughly tested before being released.

**Comment by Hurricane31337** [comment]
Oh, this is awesome to hear! Sorry, I wasn’t able to find it anywhere, so I thought I just ask here.
I’ll wait until it is safe to be released then, of course. 👍

**Comment by benjaminmcd** [comment]
@tb205gti Is there documentation anywhere for how this could be installed? Thanks!
